### ISSUE TITLE
It's elephone s7 for x20/x25

### ISSUE THREAD

**Issue by bju2000** [end222/lineage_device_omega#9]
It's a kernel. I hope it helps.
https://github.com/elephone-dev/S7-Kernel
https://github.com/flar2/Elephone-S7
https://github.com/Deepflex/android_kernel_elephone_s7

**Comment by end222** [comment]
Sadly it doesn't help since the drivers are different for each device. The only kernel source we could use is the one for our phone, we cannot port kernel sources from other phones (it is possible but requires a lot of knowledge and time)

_Sent from my Xiaomi Redmi Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
